//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAtr.DAL.Model_
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderArea
    {
        public int SliderAreaId { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string PathImg { get; set; }
    }
}
