//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAtr.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderArea
    {
        public int SliderAreaId { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string PathImg { get; set; }
    }
}
